#!/bin/python3
#coding:utf-8

import sys

print(sys.argv)

print('----',sys.exit('I will be back.'),99999)
print('exited')
23
990
<_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>
<_io.TextIOWrapper name='tt' mode='at' encoding='UTF-8'>
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
<_io.TextIOWrapper name='<stdin>' mode='r' encoding='utf-8'>
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>
